### ISSUE TITLE
reDesign *light*

### ISSUE THREAD

**Issue by IvenZ** [socia-platform/htwplus#108]
Sachen, die etwas länger in den Köpfen rumschwirren, habe ich hier mal verewigt.

**Comment by IvenZ** [comment]
Was wurde geändert?
"Mein Newsstream" ist rausgeflogen.
Der Block ist rausgeflogen.
Anstatt des Blocks gibt es nur noch den Content-Bereich der sich mit abgerundeten Ecken
und einem Shadow vom Hintergrund abheben soll.
Der Hintergrund ist nicht mehr normales weiß. Ich habe eine leichte Textur verwendet.
Über das "Muster" lässt sich sicherlich noch streiten, aber ich finde den Kontrast zum Content-Bereich damit besser hervorgehoben.

Die Landing-Page ist im Moment nicht ganz an das "neue Design" angepasst.
Loggt euch mal ein und sagt mir was ihr allgemein davon haltet.

**Comment by IvenZ** [comment]
achso, könnt ihr euch auf dev angucken.

**Comment by FabiApfelkern** [comment]
Es ist auf jeden fall besser als vorher. Aber so richtig gut finde ich es nicht. Es wirkt nicht so professionell. Und auch nicht zeitgemäß. Kann es aber nicht in Worte fassen. Ich frage mich immer warum man diesen Container überhaupt braucht. Man baut den hin, dann ändert man Hintergrund damit man ihn sieht. Aber er hat gar keine Funktion. Ich würde gerne mal was sehen ganz ohne Container. Mehr mit dem eigentlichen Inhalt spielen. Und natürlich mehr flat! :)
Aber trotzdem gute Richtung. Danke!

**Comment by TeNNoX** [comment]
So ein Zufall... :D
Ich hab in der letzten Zeit auch hin und wieder mit dem Design rumgespielt.
Hatte auch noch ein paar Ideen zu den Tabs.

**Comment by FabiApfelkern** [comment]
Als Beispiel noch eben diese Issue-Seite. Kein Rahmen oder so. Nur Content.

**Comment by TeNNoX** [comment]
@FabiApfelkern 
http://i.gyazo.com/3fc75c271dd716d963926a0ce502c0e7.png
So einfach geht das nicht, ich finde das so nicht schön.

**Comment by TeNNoX** [comment]
Eine Idee, die ich für die Tabs hatte:
http://i.gyazo.com/e338474783bb743c78dae0e6b23817d5.png
Ist aber nicht ganz passend zu dem restlichen Design.

**Comment by IvenZ** [comment]
@TeNNoX gewöhn dich mal bitte dran, dass die Tabs jetzt Schriften haben ^^
Das werden wir erst einmal so lassen.

Bzgl mit dem Inhalt spielen:
Ohne Container funktioniert vielleicht für die Streams ganz gut.
Aber auf den Übersichtsseiten sieht das etwas komisch aus wenn das einfach irgendwie so im Raum hängt und keinen Bezug zu irgendeinem Rand oder so hat.
Vorallem irgendwelche Trenner, also horizontale Linien

**Comment by IvenZ** [comment]
@FabiApfelkern Habe noch mal den privaten Newsstream ohne irgendwelche Border, Shadows oder Radiuses gemacht. Würdest du das so akzeptieren?  ^^

**Comment by IvenZ** [comment]
Da die neue Filterfunktion ins neue light-Design einfließen sollten, wurde das hier nebenbei auch noch weiter entwickelt. Hauptsächlich gerade gezogen.

**Comment by IvenZ** [comment]
auf live deployed
