### ISSUE TITLE
Newsstream-Inhalte filtern

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#111]
Filtern der Posts auf dem Newsstream nach:
 - Gruppe
 - Profil-Posts
 - Kurse
 - Favoriten

**Comment by IvenZ** [comment]
Ich habe mir überlegt das in einem Dropdown mit Multiselect zu machen.
http://davidstutz.github.io/bootstrap-multiselect/

Wenn jemand eine schönere Idee hat, dann her damit. Am Wochenende fange ich an :)

**Comment by FabiApfelkern** [comment]
Ganz spontan bin ich gegen Dropdown. Das ist ja ein zusätzlicher Klick. Nervt mich auf anderen Seiten auch oft. Aber würde mich jetzt nicht dagegen wehren.

**Comment by FabiApfelkern** [comment]
Wie wäre es mit horizontal sortierten Buttons, die man einzeln aktivieren kann und damit den Filter einschaltet.

**Comment by IvenZ** [comment]
Hatte ich zuerst auch im Sinn. Allerdings wird es meiner Meinung nach problematisch, wenn wir doch mal mehr als 4 Filter haben. Auch die Beschreibung der Filter wollte ich nicht auf ein Wort beschränken.
Bei einer horizontalen Anordnung kann es also passieren, dass eine gesamte Zeile mit Filter beschrieben ist.

**Comment by IvenZ** [comment]
Hier noch mal 2 Fragen :)
@FabiApfelkern Hast du dir das eher so wie bei Google+ vorgestellt?

![image](https://cloud.githubusercontent.com/assets/1950407/7539834/0b89bdcc-f5aa-11e4-9952-0c6ccbecbf82.png)

Dann könnte man natürlich die Dropdown weglassen.
Ich bin nämlich eher von einem Multiselect ausgegangen.

**Comment by IvenZ** [comment]
So, ich habe gemerkt, dass ich mit dem aktuellen Stand nicht viel Spielraum für Filter habe.
Also habe ich noch mal die Post-Logik aufgeräumt.
Die Query setzt sich nun aus atomaren Abfragen zusammen.
Das ermöglicht eine präzise Filterung und ist offen für Ergänzungen.
Damit wurden auch ein paar Bugs behoben (z.B war es früher möglich, dass man immer noch Posts in einer Gruppe angezeigt bekommt, obwohl man sich nicht mehr in dieser Gruppe befindet. Auf der einen Seite kann man zwar sagen, "klar, ist doch der eigene Post und den darf ich immer sehen". Ich finde allerdings, dass bei einem Post in einer Gruppe, man sein "Post-Recht" der Gruppe überträgt. Und wenn man nicht mehr Mitglied ist, darf man diesen Post eben nicht mehr sehen).

Zusätzlich habe ich Variablennamen und Kommentare schon leicht in Richtung "Kontakte" geändert.
Wir wollen ja irgendwann von "Freunden" weg.

Im nächsten Schritt werden dann die Filter bestimmt und implementiert.

**Comment by IvenZ** [comment]
Ok, der aktuelle Stand ist aufm Develop und kann getestet werden.
Ich werde selber noch ausgiebig testen.
Wenn bis nächste Woche keine Anmerkungen sind, werde ich es deployen :-)

**Comment by TeNNoX** [comment]
![send](https://cloud.githubusercontent.com/assets/2084639/7688445/b819e538-fda4-11e4-8c0b-708352c6c68d.png)

**-> Design-Vorschlag (Mockup):**
![send](https://cloud.githubusercontent.com/assets/2084639/7688459/d43f0252-fda4-11e4-97c9-5cb10e302cd3.png)

- **Filter:** margin oben reduziert
- **Filter:** margin unten entfernt
- **Filter:** Farbe von aktivem Filter auf schwarz, inaktiv auf grau
Aber auch allgemeine Sachen dabei:
- padding beim main container einheitlich gemacht
- die Buttons beim Post-Entwurf an die Textarea 'angekuschelt' (Ist auch nur ein Vorschlag, ich bin selbst noch nicht so ganz zufrieden damit...)

**Comment by IvenZ** [comment]
Danke fürs anschauen @TeNNoX 
Ich habe gerade noch mal eine aktuelle Version aufm Dev deployed.
Da sind ein Paar der von dir angesprochenen Design-Sachen schon realisiert.

Ich werde morgen noch ein bisschen rumspielen.
Allerdings auch aus bekannten Gründen nicht so viel Zeit ins Styling stecken.

Der Favoriten-Filter zeigt dir im Moment alle die von dir geschrieben Posts auf deinem Stream an.
Das ist so eine Art "Eigene Posts"-Light. Bei dem werden ja auch Posts aus Gruppen und co. angezeigt.

Der Favoriten-Filter ist im Moment auch noch eine Art Platzhalter für die wirklichen Favoriten.
In einem nächsten Schritt soll es ja möglich sein, Posts zu liken/favorisieren. Diese werden dann unter diesem Filter angezeigt.

Nun verstanden?

**Comment by TeNNoX** [comment]
Aaaaalles klar :) :+1: 
Naja, ich finde es verständlich, dass wir erstmal keinen Aufwand in ein redesign stecken wollen, aber für mich sind z.B. solche Sachen wie unsymmetrisches Padding ein Dorn im Auge... So Kleinigkeiten kann man doch machen :P

**Comment by FabiApfelkern** [comment]
Danke Iven!
1. Sieht erstmal gut aus,
2. Kannst du "Die Query setzt sich nun aus atomaren Abfragen zusammen" genauer erklären?
3. Sachen die anders sein sollten:
 - Ich finde die Tooltips unnötig und hässlich an der Stelle. Entweder man versteh, dass es ein Filter ist oder nicht. Der Text in den Tips gibt auch nicht mehr Informationen
 - Favoriten ist an der Stelle garnicht klar, das sollte erstmal raus, bis es das wirklich gibt
 - Es tut mir leid, aber diese kleinen Filer-Icon rechts und links sind für mich voll daneben, 
Wenn unbedingt, dann bitte nur auf einer Seite. 

4. Sachen die nett wären

- Das Styling ist wirklich nicht ganz so toll, ich weiß wir verweden darauf keine Zeit mehr, aber .....
- Am meisten stört mich der schwarze Balken als Highlighting, der sieht aus wie ein Trauerstreifen. Vielleicht mal unser Orange probieren?
- Mal darüber nachgedacht so eine Buttongroup (http://getbootstrap.com/components/#btn-groups) über die ganze Breite zu verweden?

**Comment by IvenZ** [comment]
So, ich habe eure Vorschläge mal aufgegriffen und noch mal geändert.
Ich persönlich finde die Button-Gruppe etwas zu "fett". Auch die kleinste Größe wirkt für mich etwas aufdringlich. Die in der Luft hängenden Links finde ich zwar auch nicht optimal, wären aber in der jetzigen Version mein Favorit.

 @FabiApfelkern 
Für die Generierung des Newsstreams sind mehrere WHERE-Clauses in der Abfrage nötig.
Jede WHERE-Clause ist vorher definiert und erfüllt genau eine Abfrageeigenschaft. 
Je nach Filter werden verschiedene WHERE-Clauses zusammengesetzt und bilden nachher das fertige Query.

Die Umsetzung ist im Moment noch nicht so hübsch und muss noch mal überarbeitet werden.
Das hat allerdings noch etwas Zeit bis wir im nächsten Schritt irgendwann einen Newsstream zum selber zusammenklicken anbieten.

Da muss ich aber noch mal bissel länger recherchieren wie man sowas macht.
Ich denke das macht dann vielleicht auch erst/eher Sinn, wenn wir mit dem Frontend noch mal Richtung SPA umsteigen.

**Comment by TeNNoX** [comment]
Ich finde die Version 1 deutlich besser...
Wie wäre es mit einem farbigen 'Trauerbalken' hier: ?
https://cloud.githubusercontent.com/assets/2084639/7688459/d43f0252-fda4-11e4-97c9-5cb10e302cd3.png

Oder wie wäre es mit sowas:
![unbenannt](https://cloud.githubusercontent.com/assets/2084639/7700163/f22f88a4-fe1c-11e4-850a-bd4a416fdcd0.png)

**Comment by FabiApfelkern** [comment]
@IvenZ Kannst du das mit den Dropdown mal ausprobieren. Glaube mittlerweile das wäre am Besten.

**Comment by IvenZ** [comment]
ok, ist deployed.
wie stellt ihr euch das mit der Anzeige des aktuellen Filters vor?
Ich habe es für den Moment mal so gemacht, dass die Buttonbeschriftung mit dem aktuellen Filter ergänzt wird.

**Comment by FabiApfelkern** [comment]
Ich finde es ganz Klasse so!!

**Comment by IvenZ** [comment]
So, habe den anderen Filter rausgenommen und den finalen(?) Button eingebaut :)
Habe ihn noch mal eine Stufe kleiner gemacht.

**Comment by ryad-eldajani** [comment]
Ist echt nice geworden.

**Comment by IvenZ** [comment]
auf live deployed
