### ISSUE TITLE
Facettensuche

### ISSUE THREAD

**Issue by IvenZ** [socia-platform/htwplus#116]
Wollte ich eigentlich schon damals realisieren.
In einer ersten Version werden Facetten für Personen realisiert.

**Comment by IvenZ** [comment]
So, hier ist auch mal wieder etwas passiert.
Auf Develop könnt ihr euch den aktuellen Stand angucken.
Bisher gibt es nur User-Facetten.

**Comment by FabiApfelkern** [comment]
Cool! Ich schreibe nochmal mehr dazu. Mir ist nur ein Fehler aufgefallen. Einmal nach Semester 3 filtern. Dann sieht mann 22 Ergebnisse. Man kann trotzdem ewig weiterscrollen.

**Comment by FabiApfelkern** [comment]
Liegt wohl daran, dass die Get-Parameter nicht an den AJAX Aufruf weitergegeben werden.

**Comment by IvenZ** [comment]
Jap, das kann sein. Guck ich mir noch mal an, danke.

**Comment by IvenZ** [comment]
QuickFix xD

**Comment by IvenZ** [comment]
So, aktueller Stand ist aufm Dev.
Hinzugekommen ist noch eine Facette für Gruppen-Ergebnisse.

Wenn euch eine Kategoriesierung für Posts einfallen, lasst es mich wissen. 
Ansonsten kann das hier ein bisschen getestet werden.

**Comment by IvenZ** [comment]
deployed
