### ISSUE TITLE
Content improvements

### ISSUE THREAD

**Issue by IvenZ** [socia-platform/htwplus#123]
Nachdem ich das Grid Design noch mal nachgezogen habe, möchte ich hier ein paar Features dafür entwickeln. Das wird verschiedene Seiten betreffen.
Im ersten Schritt vermutlich die Gruppendetail-Seite und der Newsstream.

**Comment by IvenZ** [comment]
Soooo, der aktuelle Stand ist aufm Dev zu finden.

Mit mit neuen/alten Grid-System ist nun eine rechte Spalte Content-Boxen hinzugekommen.
Diese ist aktuell auf der Newsfeed- und Gruppennewsfeed-Seite zu finden.
Es soll aber nach und nach für weitere Views nachgezogen werden.

Ich verfolge damit so ein paar Ziele.
1. Ich möchte Dinge schneller erreichen können (nachm einloggen z.B. meine Kontakte oder Gruppen)
2. Ich möchte die Navbar zum Teil rausnehmen:
Sie waren uns ja schon immer so ein halbes Dorn im Auge. Auf dem Gruppennewsfeed sind soweit alle wichtigen Informationen aus den Tabs herausgezogen worden. I.d.R in einer Light-Version (z.B Medien)
Es wirkt nicht zu überfüllt und wichtige Dinge (z.B mal schnell auf eine Datei in der Gruppe zugreifen) sind möglich.

Das Ganze hat natürlich noch einen Prototyp-Charakter.
Styling und Informationsart und -form sind immer verhandelbar :)

Implementiert ist das ganze aktuell für Medium devices (Desktops (≥992px))
Wird die Seite kleiner, verschwinden die Boxen.

Aber genug geredet. Guckt es euch einfach mal an und sagt mir, was ihr davon haltet.
Gerne auch am Freitag :-)

**Comment by FabiApfelkern** [comment]
Ich bin sehr unsicher was diese Sidebar angeht. @IvenZ Du hattest mich mal gefragt und ich war dagegen. Ich weiß immer noch nicht was das soll. Auf der Gruppen-Seite ist es ok, aber auf der Startseite nimmt es nur Platz weg. Das ist voll der 90er Jahre Forum Style. Wir haben doch die Suche um alles schnell zu finden. Ich fand es immer gut das alles so aufgeräumt bei uns ist. Dieses ganze Konzept von irgendwelchen Quick-Links ist meiner Meinung nach voll überholt.

**Comment by IvenZ** [comment]
Hey Fabi, vielen Dank für dein Post.
Ich weiß, dass du dagegen warst :)
Das hält mich ja aber noch nicht ab ;-)
Ich glaube du hast auch gesagt, dass du es mal sehen müsstest.

Was die Sidebar auf dem Newsstream angeht, bin ich nach und nach deiner Meinung.
Ich finde es nicht mehr ganz so hübsch wie am Anfang und es ist richtig, dass Gruppen und Personen eigentlich wunderbar über die Suche zu erreichen sind. Dennoch stelle ich selber bei mir fest, dass ich Gruppen z.B überhaupt nicht über die Suche ansteuer. Weil mir der Name nicht einfällt. Bei Personen ist das anders....

Für die Gruppen-Seite finde ich es jedoch super. Es komplementiert einfach die ganze Gruppe irgendwie und macht sie "spannender". Die Informationen, die es zu einer Gruppe gibt, sind sauber und ordentlich dargestellt.

Ich habe auch noch mal ein bisschen dazu gegoogelt.

http://alistapart.com/article/content-out-layout
> "Grids do not exist in a vacuum. They exist in relation to the content."

Ich glaube wenn man sich daran bissel orientiert sind so ne "Sidebars" noch nicht 90er Jahre Style und haben durchaus eine Daseinsberechtigung :)
Ich nehme auch stark an, dass einfach dieses 2-Spalten-Box-Layout-Style von der Optik viel kaputt macht. Ich glaube wenn das irgendwie fließender integriert wäre, würde das einiges hermachen.

**Comment by TeNNoX** [comment]
Also die Gruppen-Sidebar als Admin gefällt mir, auf der Homepage finde ich sie im Moment auch eher unnötig, aber sie ist bei mir auch fast leer...

Und ich würde Links und Gliederung usw. eher links vom Content erwarten. Optionen und Informationen rechts.

Und wieso nimmt die Sidebar etwas vom main-container weg? Kann die nicht bei Bedarf daneben?
Ist sonst komisch, auf manchen Seiten hat man die volle Breite und auf manchen nicht...

Und den genauen Inhalt und die genaue Funktion halte ich auch noch für Diskussionsmaterial :P

**Comment by IvenZ** [comment]
So, ich habe noch mal ein paar Anpassung gemacht.
- Es gibt nur noch einen Info und Options-Container für die Gruppen-Newsstream-Seite.
- Navtabs habe ich rausgenommen
- Medien-Container ist rausgeflogen, dafür gibt einen Link innerhalb des Info-Containers
- Mitglieder werden nur durch Avatare angezeigt (hover: kompletter Name)
- Fixed positioniert, damit es an der Seite mitscrollt.

Könnt ihr damit umgehen oder wollt ihr doch wieder die alte Version? :-)

**Comment by IvenZ** [comment]
@FabiApfelkern 
Ich werd damit doch nicht glücklich :-(
Ich dachte ich könnte das 1,2,3 fertig machen aber irgendwie gefällt es mir alles nicht.

Wollte gestern das Profil umstellen aber das passt vorne und hinten nicht.

Ich weiß aber auch, dass mir das aktuelle nicht gefällt. Ich dreh mich aber im Kreis, wenn ich versuche etwas neues zu schaffen. Meinst du wir können noch mal drüber quatschen?

**Comment by FabiApfelkern** [comment]
Natürlich können wir darüber reden. Am WE irgendwie.... Schreib mich an wenn ich online bin.

**Comment by IvenZ** [comment]
:+1:

**Comment by IvenZ** [comment]
Aktueller Stand ist auf dev.
Es ist keine finale Version.
Soll aber die Basis für die Besprechung sein :-)

**Comment by FabiApfelkern** [comment]
Der neue post style sieht super aus!

**Comment by IvenZ** [comment]
merged in master
