### ISSUE TITLE
Search shows less results than it promises

### ISSUE THREAD

**Issue by TeNNoX** [socia-platform/htwplus#125]
![screenshot](http://i.gyazo.com/f987bfa1c35124592a1b498739489458.png)

Sind 3 Ergebnisse statt 5... 
Die Gruppen und Kurse fehlen

**Screenshot kommt vom dev** - auf dem Master passiert das auf den ersten Blick nicht...

**Comment by IvenZ** [comment]
:)
Brauchst du aktuell die Suche?
Der Elasticsearch-Dev-Index ist noch auf dem alten DB stand.
Deshalb passt das nicht.

**Comment by TeNNoX** [comment]
Alles klar :P

Ist das zu zeitaufwändig, oder könnte man den index nicht beim Start einmal auffrischen?

**Comment by IvenZ** [comment]
Nö, könnte man durchaus mal machen.
Ich habe noch ein paar andere ES Verbesserungen. Ich notiere es mir mal.

ps: Ich habe den Index auf Dev mal neu gemacht. Kann es sein, dass auf der Gruppen-Ergebnissseite die Pagination nicht funktioniert?

**Comment by TeNNoX** [comment]
Funktioniert bei mir...

ich close mal ;)
