### ISSUE TITLE
Create Un-Branded Socia Version

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#133]
We do need an un-branded version of Socia, for demo purposes. 
This includes:

- Removal of every HTW reference
- Change of color schema into a neutral style
- Removal of references to HTW addresses in the code (e.g. LDAP address)
- Removal or renaming of course feature
- Removal of study course field in profile
- Possibility to create an non LDAP account (register)
- ...

**Comment by IvenZ** [comment]
check

**Comment by IvenZ** [comment]
schau mal, ob dir das soweit zusagt.

**Comment by FabiApfelkern** [comment]
Danke. Weiß noch nicht wann ich das schaffe. Kannst du vielleicht ein zwei Screenshots posten?

**Comment by IvenZ** [comment]
Jo, schaff ich aber auch erst wieder am WE

**Comment by IvenZ** [comment]
hier ein paar Screens...

![landing](https://cloud.githubusercontent.com/assets/1950407/11323269/c5a00d9c-910e-11e5-93b9-778224737949.png)

![groups](https://cloud.githubusercontent.com/assets/1950407/11323276/ef0d62f6-910e-11e5-80be-f1e5ac785b96.png)

![creategroup](https://cloud.githubusercontent.com/assets/1950407/11323277/f172c464-910e-11e5-92a6-10c56eab8f17.png)

![editprofile](https://cloud.githubusercontent.com/assets/1950407/11323279/f47063a6-910e-11e5-8ae1-17a7cbe831f6.png)

**Comment by FabiApfelkern** [comment]
Danke erstmal! Sehr gut. Ich übernehme es von hier.

**Comment by FabiApfelkern** [comment]
Ich hab ein neues Theme rübergelegt und das ganze hier in ausgelagert: https://github.com/socia-platform/socia

**Comment by IvenZ** [comment]
sehr schön. habe dann noch letzte branding-änderungen vorgenommen und mach dann hier zu :-)
