### ISSUE TITLE
Websocket not working on production

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#143]
The websocket (hence the real-time notifications) is not working on production. It seems that the wss:// protocol is not configured correctly and redirects to https://plus.... Can be monitored with the network console of Chrome.

**Comment by FabiApfelkern** [comment]
I fixed it on my Socia fork with the following nginx config: https://www.nginx.com/blog/websocket-nginx/
But for Plus we are using Apache, aren't we?

**Comment by IvenZ** [comment]
yessss

**Comment by FabiApfelkern** [comment]
Have you changed anything recently?

**Comment by FabiApfelkern** [comment]
I cannot access the server, can I? I have no HTW VPN anymore.

**Comment by IvenZ** [comment]
not necessary. did you try root or local? use local to access the server (dropbox server sheet)

**Comment by FabiApfelkern** [comment]
Yes this is working. Thanks! I will have a look soon.

**Comment by FabiApfelkern** [comment]
It's fixed!
