### ISSUE TITLE
Notification for new media in folder not working

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#145]
When you upload a new file to a folder no notification is created. The reason is that a folder has no group assigned to it. That's why the notification is never created: https://github.com/socia-platform/htwplus/blob/master/app/models/Media.java#L64

I'm not sure what the best way to fix it is? Probably always set a group for a folder.

**Comment by IvenZ** [comment]
my fault
i only tested it with media in root folders
now it should work
+ correct notification-link if a media is within a subfolder

**Comment by IvenZ** [comment]
deployed
