### ISSUE TITLE
Avatar selbst wählen

### ISSUE THREAD

**Issue by IvenZ** [socia-platform/htwplus#15]
Hatten das Thema ja schon auf dem Tisch.
Und haben festgestellt, dass es keine einfache Kiste ist.

Aber ich denke, dass das ein "must have" feature ist, was wir in irgendeiner Weise anbieten sollten.

Was mir spontan einfällt:
Bild mit fester Breite und Höhe, so wie das damals in Foren gehandhabt wurde.
Dann müssen wir uns über das resizen, oder den gewünschten Bildausschnitt keine Gedanken machen.

Bild von gravatar holen. Ich weiß zwar nicht genau wie man sie einbindet, aber irgendeinen (einfachen) Vorteil muss dieser Service ja haben.

**Comment by De3pBlu3** [comment]
jo ich seh mir das mal an...das ist das Problem, wenn es an allen Stellen unterschiedlich gemacht wird :-D

**Comment by IvenZ** [comment]
Habe noch mal ein bisschen getestet:

Zu klein:
100x100 in bmp, tif, gif, jpeg, png -> alles wird richtig erkannt.

Passend:
250x250 in bmp, tif, gif, jpeg, png -> alles wird richtig erkannt.
Bei jpeg ist mir aufgefallen, dass ein abgebrochenes Bild nicht wieder geladen werden kann.
Also jpeg auswählen, abbrechen, wieder auswählen -> Seite macht nichts.
Bei png passiert das nicht.

"Zu groß":
10000x10000 in bmp, tif, gif, jpeg,png -> alles richtig erkannt.
Allerdings läd ein 10kX10k png Bild (308kb) sehr lange.
Der Ladebalken dreht sich ungefähr eine Minute bis man zur Vorschau kommt.
Auch das Speichern dauert dann ein paar Sekunden länger.
Es hat auch nicht immer geklappt. Mal ist er einfach so ausgestiegen.
Das rechtfertigt vielleicht auch die zwei entstandenen NP Exceptions.

Hier der wichtige Teil aus der Log: 
http://pastebin.com/vcga6GJz

Vielleicht reicht einfach eine obere Begrenzung.
Da kenn ich mich allerdings nicht so aus.

ps: Vom Handy klappts auch. Geht sogar sehr gut. Über die Bibliothek kann ich wunderbar auf meine Handybilder zugreifen. :+1:

**Comment by De3pBlu3** [comment]
So die styling bugs sollten jetzt weg sein...Änderung bisher nur im Feature Branch!

**Comment by IvenZ** [comment]
merged in master

**Comment by TeNNoX** [comment]
Das "Avatare von http://www.afterglow.ie" im Impressum kann doch weg, oder?

**Comment by IvenZ** [comment]
Jo.
