### ISSUE TITLE
Markdown in Comments

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#153]
Please check the comment field in Firefox. The placeholder is cut of. 
And I'm not that happy with the integration into the comment field. It looks somehow strange and more important it is not possible to hide it again. It should hide when you click outside of it.

**Comment by IvenZ** [comment]
1. can you please test the master branch, its already merged.
2. "looks somehow strange" .. this is always our problem ;-)
good point to hide it. maybe it makes a bit less strange :D

**Comment by IvenZ** [comment]
hmmm
"click outside of it" = blur event?

not really convenient. now every time i want to drag&drop a file, the editor disappears.
other suggestions? maybe a cancel button?
