### ISSUE TITLE
Frontend Features

### ISSUE THREAD

**Issue by De3pBlu3** [socia-platform/htwplus#29]
_This issue should be a collection of frontend things and little bugs or feature ideas._

## Global
* ~~update to new Bootstrap version~~
* used icon classes out of config file for customizing frontend (LESS necessary?!)
* frontend valid to HTML5? + HTML5 features

## Special
* truncated group header are trimmed vertically
* ~~alternative favicon when notification was received~~
* restyle group info modal
* own group invites not visible

## Posts
* ~~Date mapping ('Today', 'Yesterday' ...)~~
* Char counter
* Smilies
* 'light' markdown (bold, italic, enumerations, ...)
* inline pictures
* ~~inline links~~

**Comment by De3pBlu3** [comment]
@ryad-eldajani Dein Commit https://github.com/socia-platform/htwplus/commit/58b2686e9f8378219bd973eb774c514246d8ec1c wird leider nie im Master landen, da wir Feature-Branch basiert arbeiten ;-)

**Comment by ryad-eldajani** [comment]
Wieso sollter der nicht in den Master gemerged werden können? Der Commit ist doch in dem Branch https://github.com/socia-platform/htwplus/tree/29_frontendFeatures .

**Comment by De3pBlu3** [comment]
Ach in dem ist der auch drin?! Na dann natürlich schon, sry. Dann sollte es
nur mal nen Pull Request geben... vielleicht solltest du dann mal den
Master in Frontend Features mergen.
Am 25.01.2015 09:49 schrieb "Ryad El-Dajani" <notifications@github.com>:

**Comment by De3pBlu3** [comment]
Aber aufm Dev läuft das gerade auch nicht?! Also sieh dir das mal bitte nochmal an, dann teste ich das und mach dann den Pull Request.

**Comment by ryad-eldajani** [comment]
Der Commit ist zwar im develop Branch, aber aus meiner Sicht offenbar auf dem Dev-Server nicht deployed. Ich bin da gerade auch etwas ratlos, warum das nicht auf dem Dev drauf ist. @IvenZ Hast du eine Idee, woran das liegen könnte bzw. könntest du mir den Gefallen tun und im Jenkins nachschauen, ob es evtl. ein Problem gibt?

**Comment by IvenZ** [comment]
Es war vermutlich mal aufm Dev.
Da wir ein paar single commits aufm Master hatten, habe ich im Dezember nen neuen Dev erstellt.
Und da war dann der 29er wohl nicht mehr drin.

Ich habe ihn jetzt noch mal reingemerged...

ps: schönes Beispiel warum feature Branches ganz n1 sind.

**Comment by ryad-eldajani** [comment]
Super, danke dir!

**Comment by IvenZ** [comment]
was ist eigentlich mit diesem branch/issue? das zeug ist noch nicht im master und dümpelt irgendwie seit 3 monaten hier rum.

sowas ist kacke.
wir sollten das issue-system nicht dafür missbrauchen um irgendwelche mehrdimensionalen features festzuhalten.

ein issue/branch - ein problem.

hier sieht keine sau durch.
@ryad-eldajani du hast hier ein paar dinge gemacht, oder?
die sind in sich konsistent und können deployed werden?

**Comment by ryad-eldajani** [comment]
@IvenZ Hab diesen Commit gepushed https://github.com/socia-platform/htwplus/commit/58b2686e9f8378219bd973eb774c514246d8ec1c . Offenbar hat @FabiApfelkern aber noch einen Fehler entdeckt: https://github.com/socia-platform/htwplus/issues/79 .

Den muss ich unbedingt beheben, bevor wir den mergen können. Ansonsten ist mein Beitrag konsistent, ja :)

**Comment by De3pBlu3** [comment]
Das war auch nie als Issue als Grundlage für irgendwelche Branches gedacht...es sollte mehr als Ideensammlung dienen...

**Comment by IvenZ** [comment]
merged in master
