### ISSUE TITLE
EMail Design

### ISSUE THREAD

**Issue by IvenZ** [socia-platform/htwplus#43]
Da die Notifications nun auch er Mail rausgehen, sollten wir uns überlegen, wie wir diese Mails designen.
Deshalb möchte ich mal ein paar Vorschläge sammeln.

Ich bin für ganz einfachen Standardtext ohne groß HTML einzubauen.
Das geht schnell und reicht vielleicht auch erst mal?!

Was wichtig wäre ist der Inhalt.
Posts/Kommentare/Einladungen etc. sollten auch richtig verlinkt sein.

**Comment by FabiApfelkern** [comment]
Wie in einer Feedback-Nachricht angemerkt (https://plus.f4.htw-berlin.de/post/13472) sollte in den Emailtext ein genauer Link zur betreffenden Sache.

**Comment by IvenZ** [comment]
@TeNNoX gibt es hier schon Neuigkeiten?
Hatte dich ja gebeten dir das mal anzugucken.

**Comment by TeNNoX** [comment]
Hatte ich nicht mehr dran gedacht...
Was war da die Frage?
Wie man die Mails designed?

Sonst würde mir noch einfallen:
- EasyForwarding™
- GMail Direktlink

**Comment by IvenZ** [comment]
Es gibt keine konkrete Frage :)
Es geht generell um das Ticket.
Die Notification-Mails brauchen ein Design.
Das muss nicht ausufernd sein.
Schlicht, schick und alle wichtigen Informationen.

Ein paar Anmerkungen dazu gibt es ja bereits weiter oben im Issue.

**Comment by TeNNoX** [comment]
Ich würde mich mal ransetzen, und mir was überlegen.
Hab mir schon ein paar Sachen dazu angeguckt, wie man die für mobil und desktop optimiert.

Ich mach' einfach mal einen Entwurf...

**Comment by IvenZ** [comment]
Danke

**Comment by TeNNoX** [comment]
First prototype -> RFC :)

![send](https://cloud.githubusercontent.com/assets/2084639/7577567/fdebf688-f849-11e4-928f-d80ec2d326b0.png)

**Comment by ryad-eldajani** [comment]
Gefällt mir sehr gut! Toll gemacht :+1:

**Comment by IvenZ** [comment]
Mich erschlägt es ein bisschen. Und ich sehe nicht gleich was genau Phase ist :/

**Comment by TeNNoX** [comment]
Ich fände es auch schöner, wenn man das Notification-System ein wenig
ändern würde...
Das speichern von 'gerendertem' Text in der Datenbank finde ich z.B. sehr
unschön.

Auch wäre es cool, wenn ich im Betreff den Notification Text und in der
E-Mail selbst z.B. den Kommentar selbst anzeigen würde.

**Comment by ryad-eldajani** [comment]
Jo, das Rendern war damals explizit so erwünscht, da es dann schneller ausgeliefert werden kann und nicht neu gerendert werden muss. Man kann sich natürlich über Sinn und Unsinn streiten :)

**Comment by TeNNoX** [comment]
Daaaann machen wir's halt mit einen cache ;)

Ich würde mal mein Glück versuchen, wenn ihr nicht wirklich der Meinung
seid, dass man es nicht braucht.?

**Comment by FabiApfelkern** [comment]
Ich finde das Design auch etwas heavy. Die flachen, farbigen Buttons sind cool, aber muss die Schrifft so groß und fett sein?
Wie Ryad schon sagt, man kann sich darüber streiten, ob vor-rendern oder nicht besser. Wirklich zeigen kann sich das nur wenn man wirklich viele viele Nutzer hat. Aber Denormalisierung ist auf jeden Fall ein Grundkonzept von Performance-Optimierung. Die Frage ist eher: Warum stört dich das, was willst du erreichen? Falls du einen zweiten Text brauchst, rendere den halt auch vor und speichere ihn. Das ist einfacher, als alles wieder umzubauen.

**Comment by TeNNoX** [comment]
Die Schrift mach ich noch ein wenig kleiner, ich hatte das erstmal mit mobiler Ansicht im Hinterkopf gemacht, und da sollte man mindestens ~16px nehmen.

Ich kann noch nicht so wirklich gut testen, wie es auf anderen E-Mail-Clients aussieht. (Ist ja immer so ein Problem), habt ihr da eine Idee? (Ohne einen kostenpflichtigen Service wie Litmus o.ä. zu verwenden)

Zu notifications:
Ja, mein Perfektionismus ist manchmal etwas unnötig, das gebe ich zu. Erstmal war's ja unpraktisch für die Account-Anonymisierung, da muss man die halt löschen. Meine Idee wäre halt gewesen, die Info-daten der Notification mit in der Datenbank zu speichern, dabei ist mir gerade erst aufgefallen, dass es ja das Feld 'reference_id' gibt, mit dem man sich den Text ja notfalls neu generieren könnte. Damit nehme ich meinen Verbesserungsvorschlag erstmal zurück.

Meine Idee wäre gewesen, dem Nutzer nicht nur zu präsentieren 'Neues zum Post BLABLA', sondern vielleicht direkt den jeweiligen Inhalt. Die Frage ist, ob das sinnvoll ist? 

Mein erster Punkt war, das mir wichtig ist, keine generischen Betreffzeilen zu verwenden, (z.B. 'Neues auf HTWplus') das verärgert Nutzer und führt u.a. dazu, dass manche die E-Mails gleich löschen, ohne sie zu lesen. Das weiß ich sowohl aus eigener Erfahrung, als auch aus einigen Hinweisen von z.B. Campaign Monitor...
-> Deswegen habe ich den ursprünglichen Notification-Text in die Betreffzeile gepackt. Der ist jetzt halt dann im Nachrichtentext nochmal doppelt, deswegen würde ich da gerne was detaillierteres reinpacken.

**Comment by IvenZ** [comment]
1. Ich kannte mal einen Service bei dem du verschiedene Mail Anbieter gleichzeitig testen konntest.
Aber dann teste und optimiere es erst einmal für deine Testmöglichkeiten.
Wir gucken auch noch mal drüber.

2. Bzgl. Betreffzeile: Was steht in der Betreffzeile, wenn du unterschiedliche viele Notifications hast? Was bewertest du als wichtig und was nicht? Ob 'Neues auf HTWplus' sie verägert, weiß ich nicht. Aber vielleicht können wir ja einen Zwischenweg gehen?
'Du hast X neue Nachrichten auf HTWplus'
Durch die Anzahl kann der Nutzer vielleicht gleich entscheiden wie wichtig ihm das öffnen der Mail ist.

Die Notifications müssen so oder so noch einmal überarbeitet werden.
Die Hinweistexte sind nicht optimal.
Aber nicht jetzt.

Wichtig für die Mail ist, dass es übersichtlich ist und dass es Links gibt, die zu den einzelnen Notifications führen.

**Comment by TeNNoX** [comment]
Mit der Betreffszeile habe ich mich nur auf Mails bezogen, in denen nur
eine notification ist. Sonst steht da natürlich nur 'X Neuigkeiten'...

**Comment by TeNNoX** [comment]
**Problem:**
Man braucht ja in den E-Mails für die Links die volle URL. Aber woher bekommt man die?
Afaik kann man die in Play nur aus dem Request bekommen. Auf diesen kann man allerdings z.B. im EmailService nicht zugreifen - der läuft ja asynchron... 
1. Speichern wir das beim ersten Request auf 'Application.index()' in einer Variable?
2. Oder kommt das in eine Variable in der config?
3. Oder soll das für dem EmailService beim Übergeben der Parameter an die Runnable ausgelesen werden?

Alles recht subobtimal, aber mir fällt nichts besseres ein.

**Comment by FabiApfelkern** [comment]
Es ist völlig üblich für diesen Fall die Basis URL in der Konfiguration abzulegen. So habe ich es bisher überall gesehen. Das kann man dann auf jedem Server anpassen.

**Comment by TeNNoX** [comment]
Okay, dann mach' ich dass so :)

**Comment by TeNNoX** [comment]
Aktueller Status:
![send](https://cloud.githubusercontent.com/assets/2084639/8441789/e770be54-1f7a-11e5-955e-22e349331dcf.png)
-> Soll ich das auf den develop packen? Bringt ja nicht wirklich was, da da ja smtp.mock=yes eingestellt ist...

Eine Sache noch zu den GMail actions - da gibt es relativ umfangreiche Vorschriften:
https://developers.google.com/gmail/markup/registering-with-google
... die Implementierung ist dann aber relativ einfach:
https://developers.google.com/gmail/markup/reference/go-to-action

Wäre cool, wenn ihr das mal testen könntet...

**Comment by TeNNoX** [comment]
Hab auf dem dem Server unter
**jenkins/jobs/dev.plus.f4.htw-berlin.de/workspace/conf/application.conf*
schon mal die Zeile
**htwplus.base_url="http://dev.plus.f4.htw-berlin.de"**
eingefügt...

**Comment by IvenZ** [comment]
Was hat es mit den Gmail Actions aufsich?
Sind das Guidlines wie eine Mail aufgebaut sein sollte?

**Comment by IvenZ** [comment]
Habe es gerade mit einer leeren DB und 2 Nutzern probiert...

[info] application - Created new notification for user: 7
[error] application - Invocation exception while render() template path: views.html.Emails.notificationsPlainText(null)
[error] application - Invocation exception while render() template path: views.html.Emails.notificationsHtml(null)
[info] application - Successfully sent 1 notification(s) to user 7 via email.

**Comment by IvenZ** [comment]
@TeNNoX 
Ich habe eine neue DB aufgesetzt und das mocking ausgeschaltet.
Kannst nun also auch auf dev testen.

**Comment by IvenZ** [comment]
[info] application - Created new notification for user: 1
[error] application - Error while trying to fetch notification for Post ID: 20, Recipient ID: 7: No entity found for query

**Comment by TeNNoX** [comment]
> Was hat es mit den Gmail Actions aufsich?
> Sind das Guidlines wie eine Mail aufgebaut sein sollte?

Nein, das sind diese Quick-Actions... hatte glaube @FabiApfelkern mal in irgendeinem anderen Thread vorgeschlagen... -> [das sind actions](https://developers.google.com/gmail/markup/actions/actions-overview)


> Error while trying to fetch notification for Post ID: 20, Recipient ID: 7: No entity found for query

Könntest du das mal bei dir debuggen? Ich kann's nicht reproduzieren...


> Kann man den Willkommenstext noch mal refactoren?

Meinst du eine neue Zeile einfügen, nach 'Hallo ...,' ?



Ergebnisse:
[kleinere Schrift](http://i.gyazo.com/3b3b52dc3de4eb3eb417cb71dba6435e.png)
[ohne Box](http://i.gyazo.com/b210aec9746b63fbb25678ca22d98664.png)
[oder meintest du die box? :P](http://i.gyazo.com/82bedc1fe6d31f56b7dac85ac6a3695a.png)

**Comment by IvenZ** [comment]
jo, so wie aufm 3. Bild.
Um die Notification kanns erst einmal bleiben. Dient ja dann als Link.

**Comment by IvenZ** [comment]
Habe die Fehlermeldung noch mal reproduziert und weiß woran es liegt.
Ist nichts, was jetzt unbedingt behoben werden müsste.
Also alles ok.

**Comment by IvenZ** [comment]
hey @TeNNoX 
Ich habs mir grad mal angesehen.... ich finde es ehrlich gesagt ohne Border ein bisschen besser.

Info: Für meinen 123-Branch habe ich auf Dev wieder eine alte DB mit mehr Daten eingespielt.
Um die Email Geschichte zu testen aber nicht ausversehen allen Nutzern ne Mail zu schicken, habe ich alle Email Adressen aus der DB entfernt. Wenn du testest, dann musst du den Test-Accounts wieder Email Adressen zuweisen.

**Comment by IvenZ** [comment]
@TeNNoX 
Bist du soweit durch?
Ich würde das dann diese Woche gerne noch deployen.

**Comment by TeNNoX** [comment]
Bis auf ein paar Optimierungen bin ich durch, ja :)

Wollte noch ein paar Sachen für mobil ändern und so.

**Comment by IvenZ** [comment]
ok, dann warte ich noch

**Comment by IvenZ** [comment]
deployed on master
