### ISSUE TITLE
Menuitems with name AND icon

### ISSUE THREAD

**Issue by De3pBlu3** [socia-platform/htwplus#60]
(siehe Optionsmenü bspw. in Gruppenübersichtsseite)

Zu ändern sind:
* Navbar
* TabItems

**Comment by De3pBlu3** [comment]
Also Mockup 1

**Comment by De3pBlu3** [comment]
Tab für 'Profil bearbeiten' -> falscher Text

**Comment by TeNNoX** [comment]
Von @De3pBlu3: Schriftgröße 10px

Vorschlag: einfach bessere Icons verwenden (gibt mittlerweile deutlich mehr Icons in Bootstrap)
Wenn die aussagekräftig genug sind, braucht man keine Schrift. :P

Beispiele:
![send](https://cloud.githubusercontent.com/assets/2084639/6716424/c2fa926a-cda5-11e4-803d-b05bd4250ed7.png)
![send](https://cloud.githubusercontent.com/assets/2084639/6716449/ed85a54c-cda5-11e4-91f3-eaadc3da11ad.png)

**Comment by IvenZ** [comment]
ich finde es so gut. newsstream ist allerdings noch etwas gequetscht

**Comment by De3pBlu3** [comment]
hab es nochmal ein wenig angepasst...ist aufm dev

**Comment by IvenZ** [comment]
Danke, Kevin.
Habs mir mal angeguckt. Sieht gut aus.
Du hast die Schrift in den Tabs nur verkleinert, oder?
Es sieht ein bissel so aus, als würde das eine komplett andere Schriftart sein, aber wahrscheinlich
liegt das nur an der Größe.

Kannst du vielleicht in diesem Ticket noch den "Profil bearbeiten"-Bug entfernen?

![image](https://cloud.githubusercontent.com/assets/1950407/7062696/1dc6bf10-dea0-11e4-9def-ed09c2fcd71b.png)

**Comment by De3pBlu3** [comment]
Ist geändert und auf dem Dev.
Jo ich habe nur die Schriftgröße des Textes auf 10px geändert...die Icon-Größe habe ich beibehalten.

**Comment by TeNNoX** [comment]
Ich finde die Schrift immernoch ünnötig...
Bis auf die runden Ecken und sowas finde ich das hier besser:
http://i.gyazo.com/866572c6415ccfb2dd97a6a44985f177.png

**Comment by IvenZ** [comment]
merged in master
