### ISSUE TITLE
Fixed breadcrumb

### ISSUE THREAD

**Issue by De3pBlu3** [socia-platform/htwplus#61]
Die Breadcrumbs sollten ebenso wie die Navigationsleiste am oberen Bildschirmrand fixiert werden. Dazu muss entsprechend der Style angepasst werden. Weiterhin sollte die Bedienung auf mobilen Endgeräten erleichtert werden.

**Comment by De3pBlu3** [comment]
So die noch offenen Probleme sollte jetzt der Vergangenheit angehören ;-)

**Comment by FabiApfelkern** [comment]
Bitte die Probleme nochmal nennen, der Thread ist sehr verwirrend. :)

**Comment by De3pBlu3** [comment]
Siehe Bilder in obigen Kommentaren:

![](https://cloud.githubusercontent.com/assets/1950407/4992245/eca35f14-699d-11e4-96dd-336a2ab9890a.png)


![](https://cloud.githubusercontent.com/assets/1950407/4992280/66249bbe-699e-11e4-842c-9ad9cb72036b.png)

**Comment by IvenZ** [comment]
sieht gut bei mir aus. (windows phone - IE)

**Comment by IvenZ** [comment]
Mir ist aber noch etwas anderes aufgefallen
@De3pBlu3 ich habe letztens das Hintergrundbild auf unseren Server gelegt versucht alle passenden Stellen im Code anzupassen.

Im Phone resized sich allerdings das Bild nicht mehr. 
Ich meine das hatte es noch gemacht, als ich die URL gewechselt habe.

Kannst du da bitte noch mal gucken?

**Comment by De3pBlu3** [comment]
Ist mir auch schon aufgefallen...sehe ich mir an.

**Comment by De3pBlu3** [comment]
Passt!
