### ISSUE TITLE
Collapse Package fehlt in Bootstrap

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#67]
In der customized Bootstrap.js fehlt die collapse Funktionalität. Ich habe sie erst einmal seperat mit der collapse.js ergänzt. Bitte ordentlich einbetten.

**Comment by De3pBlu3** [comment]
Ist wieder drin...

**Comment by FabiApfelkern** [comment]
Ich glaube das muss nicht groß getestest werden, wenn du sagst es geht bei den Kommentaren und der Hilfeseite.

**Comment by De3pBlu3** [comment]
Jo. Sowohl Kommentare als auch Hilfe Seite läuft :-)
