### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by IvenZ** [socia-platform/htwplus#69]
DAS Ticket für die neue Suche.
Wichtige Hinweise werden hier festgehalten.

**Comment by IvenZ** [comment]
aktueller Stand ist online.
@FabiApfelkern der Ergebniszähler für die einzelnen Suchergebnisse ist leider nicht "mal eben" gemacht. Dafür müsste ich meine ganze Suche umbauen bzw. erweitern.
Ich lass das erst einmal weg.

Wenn ich hinterher noch Zeit habe, schau ich mir das noch mal an, ok?

**Comment by FabiApfelkern** [comment]
Läuft super auf Dev. Sollten aber alle durchtesten. Dann gerne auf live.
Nur eine Sache:  Das " 1-10 von 2 in 6 ms" sollte besser sein. also von es nur 2 sind, sollte da nicht 1-10 stehen und die Zeit ist irrelevant! 
Und ich gehe davon aus du hast getestet ob wirklich alles gefunden wird. Hab ich jetzt nicht gemacht.
Ansonsten lass uns am Mittwoch über die Anzahl der der Ergebnisse reden.

**Comment by IvenZ** [comment]
ok, ist geändert.

**Comment by De3pBlu3** [comment]
An sich erstmal sehr geil...auch die Suchseite sieht jetzt super übersichtlich aus :-D :+1: 

Ein paar Anmerkungen hätte ich noch:
* Während man mit "developers" die Gruppe "Developers Developers Developers" findet, tauch diese bei der Suche nach "Developers" nicht auf.
* Wenn ich nach "develop" suche, finde ich wieder die oben genannte Gruppe und einen Post, in dem @IvenZ "Develop ..." schrieb. Sucht man jedoch nach "devel" erhält man als Suchtreffer nur noch die Gruppe "Developers Developers Developers".
* Super wäre es noch, wenn auch die Medien (natürlich nur der Gruppen, in denen man Mitglied ist) indiziert werden würden :-). Als Suchtreffer könnte man dann ein Link zu der entsprechenden Medienseite, auf der sich die gesuchte Datei befindet, anzeigen.

Außerdem habe ich auch mal mit den anderen üblichen Browsern getestet (abgesehen von Safari)...da läuft auch alles so, wie es soll!

**Comment by IvenZ** [comment]
Im letzten Update sind die meisten von euch gewünschten Punkte umgesetzt.

Medien indizieren wird wohl noch etwas größer.
Ich muss echt schauen ob ich da mit der Zeit hinkomme :-/

**Comment by IvenZ** [comment]
Ok
Develop hat nun nen Stand wie der Master.
Bitte noch einmal bis Sonntag Abend testen.

Wenn alles gut ist, dann schalte ich es Sonntag Abend dann Live.

**Comment by IvenZ** [comment]
Durch das Highlighting ist derzeit noch XSS möglich. Nicht wundern. Das kommt natürlich noch raus, bevor es Live geht.

**Comment by De3pBlu3** [comment]
Also abgesehen von meinen Anmerkungen, die noch offen sind, ist für mich alles fein :-). Hast du denn eigentlich ne Idee woran das liegt, was ich in den ersten beiden Punkten beschrieben hatte?

**Comment by IvenZ** [comment]
Das Problem sollte eigentlich behoben sein?!

**Comment by FabiApfelkern** [comment]
Was noch geil wäre: Wenn ich auf eine Person klicke mit der ich befreundet bin lade ich auf deren Stream und nicht Profil.

**Comment by FabiApfelkern** [comment]
Diese URL wirft ein Fehler: http://dev.plus.f4.htw-berlin.de/search

**Comment by FabiApfelkern** [comment]
Ach und dieses Zitat auf der Suchseite hat da meiner Meinung nach nichts zu suchen.

**Comment by IvenZ** [comment]
Frau Hüttinger, sind sie es?

**Comment by IvenZ** [comment]
Ich habe für geschlossene Gruppen und Kurse eine Landing Page gemacht.
Es gab das Problem, dass man diesen Gruppen mit der neuen Suche (speziell die Anzeige der Gruppen und Kurse) nicht mehr beitreten konnte.
Die Landing Page besteht aus nicht mehr als der Gruppeninfo + Beitrittslink.

**Comment by De3pBlu3** [comment]
Also meinet wegen kann das Zitat bleiben ;-). Jedoch finde ich die Suchseite noch nicht optimal:
* Das Alert würde ich rausnehmen, so dass man halt einfach durch leere Suche oder die entsprechende URL auf die Such-Seite gelangt.
* Wenn das Zitat bleiben soll, dann muss es aber auch bei kleinerer Auflösung umbrechen.
* Außerdem sollte das Such-Eingabefeld auf maximale Breite skalieren.
* Vielleicht wäre auch ein Titel für die Seite nicht schlecht, da die Seite sonst so leer aussieht

Hier mal ein Mockup, wie ich es schick fänden würde:
![image](https://cloud.githubusercontent.com/assets/4548411/5891285/ad380fb2-a48c-11e4-8da4-9b1c77cdbbb2.png)


Zur Gruppen und Kurs Infoseite; finde ich erstmal gut, aber daraus ergeben sich noch ein paar weiter Anmerkungen ;-):
* Den Button zur Beitrittsanfrage bitte rechts oben als Tab.
* Ansonsten sollte die Seite, damit es einheitlich wird, vielleicht das selbe Layout erhalten, wie auch das Personen-Profil (bzw. wie das Info-Modal oder die Bearbeiten-Seite einer Gruppe). 
* Mit solch einer Info-Seite könnte man nun natürlich auch das Info-Modal endlich verbannen?!

**Comment by IvenZ** [comment]
@De3pBlu3 hast du das schon fertig gestyled?
Könntest du es dann vielleicht direkt in meinen Branch pushen?

**Comment by IvenZ** [comment]
@all 
Ich habe noch Probleme mit dem Escapen.
In #62 hatten wir das Thema erlaubte Buchstaben schon mal angesprochen.
Für die Gruppen habe ich das gleich mal gemacht. @Pattern(value="^[A-Za-z0-9.!#$%&'+=?_{|}~-]+$")

Was mir allerdings im Moment noch gar nicht gefällt -> das Escapen der Posts für die Suchseite.
Ich weiß nicht wie ich das am schönsten hinbekomme.

Das Problem:
Elasticsearch return mir genau den Schnipsel mit dem gefundenen Suchwort. Das Wort wird dabei schon in <em> </em> gepackt.
Damit das im Template auch so angezeigt wird, muss es von Play mit @Html escaped werden.
Allerdings wird dann der ganze Suchschnipsel escape, d.h auch JS falls vorhanden.

**Comment by De3pBlu3** [comment]
@IvenZ Also das mit der erweiterten Suche war wie gesagt nur ein Mockup (Vorschlag), somit wäre es an dir, das umzusetzen, wenn dir das auch gefällt.

Logo und Landingpage bin ich noch in einem eigenen Branch dran.

**Comment by IvenZ** [comment]
merged in master
