### ISSUE TITLE
Auto-Pagination

### ISSUE THREAD

**Issue by De3pBlu3** [socia-platform/htwplus#70]
Automatisches Nachladen des Inhalts beim Scrolln wird integriert.

**Comment by TeNNoX** [comment]
Soll ich die alte Seitenauswahl als <noscript> drinlassen?

**Comment by TeNNoX** [comment]
PR: https://github.com/socia-platform/htwplus/pull/118

**Comment by FabiApfelkern** [comment]
Der Footer muss jetzt anders sein.
Und sagmal wird beim scrollen jedesmal die ganze HTML-Seite geladen?

**Comment by TeNNoX** [comment]
Ja, in der tat. Kann man sich anders machen... Bin jetzt erstmal in
Richtung der einfachen Lösung gegangen (Programmierer-Faulheit und so)
Aber an sich ja...

Und was machen wir mit dem footer? Immer sichtbar?

**Comment by IvenZ** [comment]
Der Footer kommt oben in den Header unter einem extra Menüpunkt. (wieso habe ich das Ding geclosed?!)

**Comment by De3pBlu3** [comment]
Nach dem Laden der letzten Seite erscheint wieder der Loading-Indicator und
bleibt stehen.

2015-06-05 13:48 GMT+02:00 Iven Zimmer <notifications@github.com>:

**Comment by TeNNoX** [comment]
Sorry, dass ich das vergessen hab :/

**Comment by TeNNoX** [comment]
Das sieht nicht ganz so super aus, in dem Drowndown.
Aber Submenus gibt es ja in Bootstrap nicht:
**"Submenus just don't have much of a place on the web right now, especially the mobile web. They will be removed with 3.0"**

![send](https://cloud.githubusercontent.com/assets/2084639/8032643/a97b003c-0dd7-11e5-8b4a-b22f1571c858.png)

Akzeptabel?

**Comment by FabiApfelkern** [comment]
Ich finde es völlig ok!

**Comment by De3pBlu3** [comment]
Dito

2015-06-08 12:22 GMT+02:00 Fabian Kirstein <notifications@github.com>:

**Comment by TeNNoX** [comment]
@De3pBlu3:
> Nach dem Laden der letzten Seite erscheint wieder der Loading-Indicator und
bleibt stehen.

Kann ich leider nicht reproduzieren... Kannst du dazu noch irgendwelche Details rausfinden?
Bzw. ist es jetzt immernoch so?

**Comment by IvenZ** [comment]
bzgl. Footer im User-Menü: Jo, kannst so lassen.
Aber bitte achte darauf, dass auf der Landing-Page der Footer vorerst so bleibt.

**Comment by De3pBlu3** [comment]
Jetzt scheint alles zu passen :-)

2015-06-08 13:35 GMT+02:00 Iven Zimmer <notifications@github.com>:

**Comment by IvenZ** [comment]
label bitte erst wieder ranhängen, wenn wieder getestet werden kann :)

**Comment by TeNNoX** [comment]
... kann es doch :P

**Comment by IvenZ** [comment]
Also bei mir läufts soweit ohne Probleme.
Kannst du aber vielleicht noch mal die Seite des ToTheTop-Buttons wechseln.
Ich erwarte ihn irgendwie immer auf der rechten Seite.

Und wenn man mit Handy unterwegs ist, wäre es vielleicht gut, wenn man nur den Pfeil anzeigt?
Das nimmt sonst ne Menge Platz weg.

**Comment by FabiApfelkern** [comment]
Können wir aus den Footer Links die ein Modal öffnen richtige Seiten machen? Finde es komisch, wenn sich aus einem Dropdown ein Modal öffnet.
Ansonsten alles sehr super!

**Comment by TeNNoX** [comment]
> Ich erwarte ihn irgendwie immer auf der rechten Seite.
Ja, dachte ich auch, aber wenn man auf der mobilen Seiten ihn rechts hat, ist der einem doch beim Scrollen im weg, oder nicht?

> ... wenn man nur den Pfeil anzeigt
Stimmt, mach ich noch :)

> Footer Links die ein Modal öffnen richtige Seiten machen
vielleicht in ein extra Issue?

**Comment by IvenZ** [comment]
Also bei mir wäre er nicht im Weg.

Ich mach das mit dem Modal dann im Master. Wollte sowieso noch mal die Footer-Links aktualisieren.

**Comment by IvenZ** [comment]
Eine Sache ist mir gerade noch aufgefallen.
Auf der Suchergebnisseite gibt es gar keine Pagination mehr. ;-)

**Comment by TeNNoX** [comment]
So, sollte soweit alles funktionieren -> ready_to_test

**Comment by IvenZ** [comment]
Danke @TeNNoX :)

**Comment by IvenZ** [comment]
jo, scrollt sich gut. :)
wenn es auch den anderen gefällt, landet es demnächst im master

**Comment by IvenZ** [comment]
läuft nun im master
