### ISSUE TITLE
Bearbeiten von Posts

### ISSUE THREAD

**Issue by De3pBlu3** [socia-platform/htwplus#71]
Selbst erstellte Posts und Kommentare sollen nachträglich bearbeitet werden können. Mindestens ein Hinweis, dass dieser bearbeitet wurde, oder gar gewisse Einschränkungen sind notwendig.

**Comment by IvenZ** [comment]
Ich bin fast dafür, dass sich ein Post nur inner von X Minuten bearbeiten lässt.
Gründe:
- Es schränkt das trollen ein.
- Nutzer lesen bereits gelesene Posts nicht mehr
- Ich kenne keinen Use Case, bei dem ich einen Post nach mehreren Stunden/Tagen noch mal komplett änder.

**Comment by FabiApfelkern** [comment]
Ich stimme voll zu! Bei FB ist es genauso.

**Comment by De3pBlu3** [comment]
Finde ich gut...machen wir so =)

Am 12. Februar 2015 um 18:42 schrieb Fabian Kirstein <
notifications@github.com>:

**Comment by FabiApfelkern** [comment]
Anforderungen:
 - Icon neben Mülltonne
 - Bearbeitung nur für x Minuten
 - Ausgegraut wenn nicht möglich mit Tooltip
 - Text wird zu Eingabefeld
 - Speichern Button daneben

**Comment by TeNNoX** [comment]
Sind doch schon Fortschritte :)
![bearbeiten](https://cloud.githubusercontent.com/assets/2084639/6397493/5a2ae07a-bde5-11e4-810f-71f7a7a8365c.png)

**Comment by De3pBlu3** [comment]
Fein :-)
Ich hoffe du hast meine Anmerkungen in 6c2506c wahrgenommen?

**Comment by TeNNoX** [comment]
Wie ist das eigentlich, sollen Posts genauso bearbeitbar sein?
War bis jetzt erstmal davon ausgegangen, da man das später ja noch recht leicht ändern kann...

**Comment by De3pBlu3** [comment]
Jo...sollte sich identisch zu den Kommentaren verhalten.

Am 27. Februar 2015 um 16:09 schrieb TeNNoX <notifications@github.com>:

**Comment by IvenZ** [comment]
@TeNNoX 
Bitte darauf achten: http://en.wikipedia.org/wiki/Unobtrusive_JavaScript

**Comment by TeNNoX** [comment]
@IvenZ Dachte ich mich schon... Aber ich dachte in dem Fall wäre das eine Ausnahme wert, da man dann nicht bei jedem neuerstellten Post die Funktion zum "anbringen" des onClick-Events ausführen müsste.

Aber gut, mache ich bei der sauberen Variante anders :P

**Comment by IvenZ** [comment]
Danke :)

**Comment by FabiApfelkern** [comment]
Du musst bei einem neuerstellten Post keine Funktion zum "Anbringen" des Events ausführen. Das geht auch automatisch in jQuery mit dem on()-Event: http://stackoverflow.com/questions/1359018/in-jquery-how-to-attach-events-to-dynamic-html-elements

**Comment by TeNNoX** [comment]
Ouuuuh... sweet :D
Danke :)

**Comment by TeNNoX** [comment]
Was passiert, wenn der User anfängt, einen Post zu bearbeiten, und aber wenn er den bearbeiteten Post abschickt, die Zeit schon abgelaufen ist?

Einfach die Seite neu laden, wenn beim Laden ein badRequest zurückgebenen wird?

**Comment by TeNNoX** [comment]
Und wenn die Session des Nutzers abläuft, während die Seite offen ist, kommt das hier:
http://i.gyazo.com/3873899eb2f4b8574587bff932361123.png

Das kann ich aber nicht so einfach beim AJAX ändern, da in dem Fall vom Server auch ein "200 OK" zurückgegeben wird... :/

**Comment by FabiApfelkern** [comment]
Sehr guter Punkt mit der Session. Ich habe mir mal ein Ticket erstellt (#91), um das global besser zu gestalten. Ignoriere das Problem erstmal. 
Wegen der abgelaufenen Zeit: Gute Frage. Vielleicht können wir für das Speichern eine Toleranzzeit einbauen. Vielleicht 10 Minuten und dann ist halt Pech,

**Comment by TeNNoX** [comment]
Also X Minuten lang ist der Button sichtbar, und Y Minuten lang kann man es noch abschicken. ?!

**Comment by FabiApfelkern** [comment]
Genau!

**Comment by TeNNoX** [comment]
Done. :)

**Comment by TeNNoX** [comment]
test this please

(sollte soweit funktionieren.)
Eine Idee, die ich noch hatte (vielleicht als extra issue?), ist dass wenn ein Post bearbeitet wurde, neben der Zeit:
![send](https://cloud.githubusercontent.com/assets/2084639/6562290/1e49bb56-c698-11e4-8967-70b7ac9f74c2.png)

**Comment by FabiApfelkern** [comment]
Es gibt zwei Branches mit 71. Nur um sicher zu gehen, welcher soll getestet werden?

**Comment by TeNNoX** [comment]
@FabiApfelkern 71_editPosts

**Comment by TeNNoX** [comment]
@FabiApfelkern Die aktuelle Branch ist jetzt 71_editPostsClean...

basierend auf dem master branch

**Comment by TeNNoX** [comment]
Was haltet ihr davon:
![send](https://cloud.githubusercontent.com/assets/2084639/6608384/cfa85c4a-c846-11e4-8373-76832e84ab49.gif)

v2 (Klick auf 'neuladen' lädt die Seite neu):
![send](https://cloud.githubusercontent.com/assets/2084639/6608843/02a6f7a6-c84b-11e4-9e16-f3161e082eff.gif)

**Comment by IvenZ** [comment]
merged in master
