### ISSUE TITLE
Überarbeitung des Profils

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#73]
Das Profil muss verfeinert werden, mehr Felder bieten. Auf das Ausfüllen der Email soll schon auf dem Stream hingewiesen werden.

**Comment by IvenZ** [comment]
Ich möchte gerne, dass man durch das Profil sieht, in welchen Gruppen eine Person ist.
Vorallem bei Dozenten.
Mir ist das jetzt schon zwei mal passiert, dass ich mir nen Kurs angucken wollte, ich zwar den Dozenten kannte, aber nicht wusste wie seine Kurse finde.
Früher hatte das mit der Ergebnisübersicht der Suche noch ganz gut funktioniert.
Ich möchte die Suche auch wieder diesbezüglich erweitern. 
Aber ich denke es ist trotzdem nicht verkehrt, wenn ich auf dem Profil der Person sehe, in welchen Gruppen/Kursen der/diejenige ist.

**Comment by De3pBlu3** [comment]
Aber dann vielleicht unter der Bedingung, dass man mit der Person
"befreundet" ist.

Am 27. Februar 2015 um 10:10 schrieb Iven <notifications@github.com>:

**Comment by IvenZ** [comment]
Würde das Ziel meines Vorhabens wieder einschränken ;)
Mit Dozenten bin ich ja nicht befreundet.
Und mit den aktuellen Berechtigungen würde ich auch so herausfinden, welche Person sich in welcher Gruppe aufhält. (finde ich auch gut so)
Es wäre nur ein bisschen umständlich und ich hätte es gerne zentral.

Was würde denn deiner Meinung nach gegen eine öffentliche "ich bin in der und der Gruppe"-Anzeige sprechen?

**Comment by De3pBlu3** [comment]
Warum bist du denn nicht mit deinen Dozenten befreundet??? Verstehe ich
nicht ;-).
Ja stimmt schon, bekommt ja jetzt bereits raus - halt nur umständlich.

Dann packen wir es halt aufs Profil...vielleicht kann man ja persönlich
noch einstellen, ob man das will oder nicht?!

Am 27. Februar 2015 um 11:34 schrieb Iven <notifications@github.com>:

**Comment by TeNNoX** [comment]
Das Layout müsste ein wenig angepasst werden...

![send](https://cloud.githubusercontent.com/assets/2084639/6845845/1f421c14-d3b9-11e4-9486-74b4163f5f60.png)

**Comment by IvenZ** [comment]
Bezüglich der Anpassung des Layouts kann man sich mal
https://www.playframework.com/documentation/2.3.x/JavaFormHelpers
angucken.
Play besitzt auch die Bootstrap Templates die wir einsetzen können.
Es ist allerdings etwas mehr Aufwand.
Ich würde sagen wir warten damit bis @FabiApfelkern sein #15 Branch vollendet hat, da er sicherlich
auch auf der Page rumspielen musste.

**Comment by FabiApfelkern** [comment]
- Refactoring
 - Neue Felder:
   - Über mich
   - Homepage
   - Socia Media Links
   - Geburstag

**Comment by IvenZ** [comment]
@TeNNoX Wie weit ist dieses Ticket hier eigentlich gekommen?

**Comment by TeNNoX** [comment]
Ich habe - glaube ich die Profilseite schon auf Bootstrap umgestellt, und
bei dem anderen ein wenig angefangen. Aber ich habe im Moment keine zeit,
mir das anzuschauen.. :/

**Comment by IvenZ** [comment]
alles klar. Danke.
Ich schau mir den Rest mal an.

**Comment by IvenZ** [comment]
Habe noch 2 Felder geadded.
@FabiApfelkern wie hast du dir Geburtstag und Social Media Links vorgestellt?

Aktueller Stand ist auf dev.

**Comment by IvenZ** [comment]
deployed
