### ISSUE TITLE
Neues Medienmanagement

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#74]
TBA - Ergebnis der Projektstudiums abwarten

**Comment by IvenZ** [comment]
Ich werde hier jetzt Stück für Stück anfangen das Medienmanagement rüber zu ziehen.

**Comment by IvenZ** [comment]
Ein erster Stand zum Folder-Management ist erreicht:

Ordner wurden mit folgendem Gedanken implementiert:

Folder ist ein eigenes Model.
Folder hat "group, account, parent" Eigenschaften die symbolisieren, ob der Folder zu einer Gruppe, einer Person oder zu einem anderen Folder gehört (wie unserer Posts).

Das Erstellen eines Folders passierts im jeweiligen Controller (Group, Account etc).
Grund:
- Das routen-naming bleibt einheitlich und übersichtlich.
- Im FolderController müsste erst wieder untersucht werden, ob es sich um eine Gruppe, Account der einen Folder handelt, zu der der erzeugende Folder eine Zugehörigkeit hat.

Refactoring der Medien:
Medien wurden den Gruppen entzogen.
Eine Medium kann nicht mehr direkt einer Gruppe zugeordnet werden.
Alle Medien werden nur noch Ordnern zugeordnet.
Diese wiederum haben dann die Zugehörigkeit zu einer Gruppen, Personen oder anderen Ordern.

Bei Erzeugung einer neuen Gruppe wird automatisch ein Medien-Root-Ordner angelegt.
Dieser ist der Einstieg für alles, was sich auf hochgeladene Medien bezieht.

Gedanke dazu:
Eine Gruppe oder ein Account könnten mehrere root-Ordner besitzen.
Vielleicht möchte man einmal verschiedene Medien in einer Gruppe unterbringen
(Hochgeladene Medien, Medien auf dem Newsstream, Bilder (Avatar, Profilhintergrund einer Gruppe selbst) usw.

Um besser auf sie zugreifen zu können sitzen sie deshalb in eigenen Ordern und sind deshalb nicht mehr direkt einer Gruppe zugeordnet.

**Comment by TeNNoX** [comment]
Ich finde ja, man sollte die Implementierung der Ordner-Besitzer anders
implementieren. Das hat mich schon beim Post geärgert...

Ich fände es sauberer, wenn man z. B. Ein Interface IFolderOwner und
IPostOwner macht, und dann Group, Folder und Account das implementieren...
Sonst besteht immer die Gefahr von Bugs, wenn man z. B. Mehrere
owner-felder gleichzeitig setzt, oder wenn man einen neuen Folder-owner Typ
hinzufügt, und irgendeine if-Anweisung den nicht berücksichtigt, usw...

**Comment by IvenZ** [comment]
Was verstehst du unter mehrere owner-Felder? Oder owner-Typen?
Kann da nicht ganz folgen :)

**Comment by TeNNoX** [comment]
> group, account, parent
Ist ja praktisch der owner von dem Ordner (und analog dem Post)...

**Comment by FabiApfelkern** [comment]
Vielen Dank für die detailliert Beschreibung. Ich bin wie immer anderer Meinung und denke, dass dein Architekturentwurf ungünstig ist. 
Ich würde in jedem Fall daraus ein eigenes Modul machen mit eigenen Controllern, Models und Libs. Und versuchen kaum bis keine Funktionalität in die Group- oder Account-Controller zu packen. Verantwortlichkeiten sollten immer klar getrennt sein, um Wiederverwendbarkeit und Wartbarkeit zu erhöhen (Naumann 2010 :)). Routen-Namen sind Schall und Rauch und sollten keine Entscheidung beeinflussen. Außerdem ist es Wurst welche Resource man welcher unterordnet. Ich denke da an folgendes Routing: /media/group/:id oder /media/account/:id. Finde es auch völlig ok, wenn die Zugehörigkeit immer erst ermittelt werden muss. Das kann man sicherlich elegant lösen. Denkbar ist auch ein Medien-Snippet, was auf den entsprechenden Seiten einfach eingebunden wird. Ich würde es wahrscheinlich nicht mal auf diese 2 Fälle group und account beschränken, sondern es irgendwie noch generischer machen....
Zu den Rechten: Ich denke hier bietet es sich an gleich mal ein besseres Rechtesystem umzusetzen. Erstmal nur für Medien und später kann es eventuell auch woanders eingesetzt werden. Aber zum Ausprobieren eine ideale Gelegenheit. Ich denke, es sollte möglich sein die Rechte einer Datei (Lesen, Ändern, Löschen, ...) explizit auf weitere Personen zu übertragen. Offensichtlichste Lösung: Ein Tabelle mit Accounts-Medien-Rechten. Geht aber bestimmt auch anders. Ich finde unser impliziten Rechtesystem sehr starr und früher oder später werden die Anforderungen da nicht mithalten. 
Zu den Root-Foldern: Finde ich eine gute Idee. Ich denke, die sollten auch klar sichtbar sein. Ein Folder für den eigentlichen Upload und min. einen für Sachen aus den Streams. Ich finde, wenn jemand im Stream direkt hochlädt (irgendwann mal..) sollte das in einem sichtbaren Ordnern landen, damit man es wiederfindet. Ganz wichtig!

**Comment by IvenZ** [comment]
uiuiui. das erzeugt ja ganz schöne wellen 
@TeNNoX was hat dich denn genau geärgert oder gestört?
wo gab es probleme?

ich bin irgendwie nicht so der richtige freund von interfaces (vermutlich auch, weil ich sie noch nie gewinnbringend eingesetzt habe) 
Was würden mir interfaces bieten, was mir die aktuelle Implementierung nicht bietet?

@FabiApfelkern Das ist eine Menge bei der mein Kopf keinen Ansatz bilden kann ^^
Was genau ist für dich ein Modul? Etwas, was wir als extra Library bei uns einbinden?
Was ist der Unterschied zu einem Medien-Snippet? 
Bei der Verantwortlichkeit geh ich mit.
Rechtesystem ist auch wieder ein sehr interessantes Thema. 
Aber auch hier fehlt mir aktuell der Ansatz im Kopf wie sowas aussehen könnte.

**Comment by IvenZ** [comment]
vorerst abgeschlossen.
drag & drop sowie upload-anzeige werden in weiteren versionen realisiert.

merged in master
