### ISSUE TITLE
Falsche Zeit in Worten

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#79]
Die Umrechung der Daten in Worte scheint nicht richtig zu funktionieren. Siehe Screenshot.
Es ist gerade 13 Uhr bei mir. Den ersten Post habe ich gestern Abend geschrieben nicht heute (in der Zukunft). Iven kann auch nicht heute Abend kommentiert haben. 

![unbenannt](https://cloud.githubusercontent.com/assets/1488424/5987968/0fe80390-a949-11e4-8090-ce8f51026050.PNG)

**Comment by ryad-eldajani** [comment]
Der 79er Branch basiert auf dem aktuellen Develop Branch.

**Comment by IvenZ** [comment]
Danke. Kann man das irgendwie gut testen?
Habe gerade ein Post verfasst und er zeigt das richtige Datum an.

**Comment by ryad-eldajani** [comment]
Ich hab heute auch viel rumprobiert, um den Fehler überhaupt nachstellen zu können :)
Am Ende konnte ich das reproduzieren, indem ich das Datum auf morgen um 11 stelle, einen Post erstelle, das Datum auf 19 stelle, einen Kommentar erstelle und dann nochmal einen Tag weiter auf 11. Am Ende hatte ich dann alles auf Heute. Mit der Joda API klappts aber alles gut. Die Date API von Java ist wohl broken by design bis Java 8.

**Comment by IvenZ** [comment]
Ok. So habe ich es auch gerade getestet. Aber das hat keinen Effekt, wenn ich das auf Dev teste, oder?
Es wird ja immer die Systemzeit von dem Host-Rechner genommen.
Also egal welches Datum oder Uhrzeit ich bei mir einstelle, er beschriftet die Uhrzeiten nach Dev-Server?!

**Comment by ryad-eldajani** [comment]
Ja genau. Es gilt immer die Serverzeit. Ist also auf dem Dev leider kaum zu testen.

On April 7, 2015 6:09:54 PM GMT+02:00, Iven <notifications@github.com> wrote:
>Ok. So habe ich es auch gerade getestet. Aber das hat keinen Effekt,
>wenn ich das auf Dev teste, oder?
>Es wird ja immer die Systemzeit von dem Host-Rechner genommen.
>Also egal welches Datum oder Uhrzeit ich bei mir einstelle, er
>beschriftet die Uhrzeiten nach Dev-Server?!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/socia-platform/htwplus/issues/79#issuecomment-90624252

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by IvenZ** [comment]
merged in master
