### ISSUE TITLE
SSL prüfen

### ISSUE THREAD

**Issue by IvenZ** [socia-platform/htwplus#83]
Spinnt schon ne ganze Weile.
Ich gucke mir das im neuen Semester mal an.

**Comment by TeNNoX** [comment]
"Diese Website verwendet ein SHA-1-Zertifikat; es wird empfohlen, Zertifikate mit Signaturalgorithmen zu verwenden, die stärkere Hashfunktionen verwenden als SHA-1."

**Comment by IvenZ** [comment]
kann getestet werden.

**Comment by TeNNoX** [comment]
Chrome auf Window 8.1:
![send](https://cloud.githubusercontent.com/assets/2084639/7494374/844fb1ac-f407-11e4-864e-e28b525b7c21.png)

**Comment by IvenZ** [comment]
wichtig ist, dass da nix rot durchgestrichen ist oder nachgefragt wird, ob man der verbindung vertrauen möchte

**Comment by IvenZ** [comment]
sollte ja wieder gehen
