### ISSUE TITLE
Account löschen

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#84]
Nutzer sollten die Möglichkeit haben ihren Account zu löschen. Erstellte Inhalte sollen anonymisiert werden.

**Comment by IvenZ** [comment]
wurdest du darauf angesprochen? :)

**Comment by TeNNoX** [comment]
Ich überlege gerade, welche Rolle der Dummy Account bekommt... Administrator oder Student?
Oder vielleicht eine vierte AccountRole 'Dummy' erstellen?

**Comment by De3pBlu3** [comment]
Jo der sollte separat behandelt werden.

Am 26. März 2015 um 01:52 schrieb TeNNoX <notifications@github.com>:

**Comment by FabiApfelkern** [comment]
Also ich denke das ist nicht unbedingt notwendig. Ich würde ihm die kleinste Rolle geben, also Student.

**Comment by De3pBlu3** [comment]
Naja zumindest für das Backend würde das reichen, jedoch sollte dieser im
Frontend eindeutig von den anderen Personen unterschieden werden können:
 * kein User-Profil (wüsste nicht, wozu das gut sein sollte)
 * keine Freundschaftsanfragen
 * eigens Popup beim hover über den Namen
 * ...

2015-03-26 10:07 GMT+01:00 Fabian Kirstein <notifications@github.com>:

**Comment by De3pBlu3** [comment]
Naja zumindest für das Backend würde das reichen, jedoch sollte dieser im
Frontend eindeutig von den anderen Personen unterschieden werden können:

*   kein User-Profil (wüsste nicht, wozu das gut sein sollte)
*   keine Freundschaftsanfragen
*   eigens Popup beim hover über den Namen
*   ...

**Comment by FabiApfelkern** [comment]
Stimmt auch wieder. Ich dachte dafür werden einfach die Links deaktiviert. Identifzieren würde ich ihn über die ID. Aber ist wahrscheinlich sauberer so.

**Comment by De3pBlu3** [comment]
Richtig...identifizieren per eigener Rolle ist auch fehlerunanfälliger,
auch wenn die ID ja unique ist. Außerdem wäre es so wiederverwendbar...

Am 26. März 2015 um 11:13 schrieb Fabian Kirstein <notifications@github.com>
:

**Comment by TeNNoX** [comment]
Hier ein paar Bedenken, die mir noch gekommen sind:

1. Da man den ja als User ausweisen muss, was kriegt der als E-Mail/Passwort?
Einfach wie beim Admin? (aus der Config) Eigentlich braucht der ja kein PW, da man sich nicht einloggen muss...

2. Was passiert mit den Gruppen, die der User erstellt hat? Müssten die Admin-Rechte da nicht an jemanden übertragen werden, der sie auch benutzen kann?

3. Das Löschen sollte eigentlich statt per Eingabe eines Satzes/des Benutzernamens eigentlich das Passwort verlangen. Falls man einen eingeloggten fremden Account vorfindet, darf man den ja nicht Löschen können...

**Comment by FabiApfelkern** [comment]
Vielen Dank! Das sind sehr gute Punkte.
zu 1. Ja denk dir einfach was aus. Die anderen Nutzer sehen das ja eh nicht

zu 2. Daran haben wir garnicht gedacht. Völlig richtig. Wir haben leider kein vernünftiges Rechtesystem in den Gruppen. Das fällt uns jetzt wieder auf die Füße. Ignoriere das erstmal. Die Gruppe hat dann keinen Admin mehr. Und wir gehen das Problem bald an. Vielleicht wird das deinen nächste Aufgabe. Muss mal gemacht werden. 

zu 3. Stimmt. Mach das so.

**Comment by TeNNoX** [comment]
4. Was ist mit den Notifications, die andere User durch den User TBD (=To Be Deleted) bekommen haben?
Ich würde ja für Löschen plädieren, aber irgendwie kann's ja sein, dass er was kommentiert hat, und andere deswegen dann nicht benachrichtigt werden...
Aber anonymisieren geht leider nicht so wirklich, weil in der Datenbank ja die Namen im Klartext drinstehen.
**Idee:** In die Datenbank Placeholder reinschreiben (z.B. '$SENDER$').
Da stellt sich mir aber die Frage, wie man den Übergang dahin realisieren würde, bzw. ob das nicht einfach zu viel Aufwand für sowas ist...

**Comment by TeNNoX** [comment]
5. Soll ich im Admin Panel noch eine Funktion hinzufügen zum Löschen von Accounts?

**Comment by FabiApfelkern** [comment]
Link kannst du einbauen. Gute Idee. Mit den Notifications müssen wir morgen mal gemeinsam besprechen. Ich kann da nicht so viel sagen. Ryad weiß da Bescheid.

**Comment by TeNNoX** [comment]
! zu beachten (Hinweis von Iven):
Sichtbarkeit der Posts vom gelöschten Account.
(vorher befreundete User dürfen sehen, andere nicht)

**Comment by IvenZ** [comment]
Da ich am Sonntag deployen möchte -> Ist das Ticket jetzt eigentlich durch? @TeNNoX

**Comment by TeNNoX** [comment]
Sollte nochmal getestet werden, aber eigentlich schon, ja...

**Comment by TeNNoX** [comment]
Habe es nochmal getestet.
Ist auf dem Develop, bitte mal jemand anderes testen noch...

**Comment by IvenZ** [comment]
@TeNNoX 
Habe gerade den ersten Test gemacht ...
Können sich LDAP User löschen?
Mein erster Gedanke war, welches PW sollen sie zur Löschung eingeben, das LDAP PW?
Habs dann ausprobiert und in nem 404 gelandet

**Comment by IvenZ** [comment]
2. Sache:
Ich finde den Namen (Anonym @HTWplus) nicht intuitiv.
Ebenfalls erscheint es so, dass man ihn noch anklicken könnte.
Mein Vorschlag wäre ihn in 'Gelöschte Person' umzubennennen und wenn er irgendwo im Feed auftaucht, dann mit grauer Schrift und nicht klickbar.

Ansonsten scheint erst einmal alles zu funktionieren :+1:

**Comment by TeNNoX** [comment]
Gut, mache ich noch :)

**Comment by IvenZ** [comment]
label bitte erst wieder ranhängen, wenn wieder getestet werden kann :)

**Comment by TeNNoX** [comment]
Habe soeben meinen eigenen Account auf dem develop gelöscht, funktioniert soweit.

**Comment by IvenZ** [comment]
sehr schön. ich kann ebenfalls lokale und ldap accounts löschen.
wenn niemand mehr etwas vorbringen möchte landet es ebenfalls im master

**Comment by IvenZ** [comment]
läuft nun im master
