### ISSUE TITLE
Posts favorisieren

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#85]
Posts und Kommentare können favorisiert werden.....
TBA

**Comment by IvenZ** [comment]
Super Feature für meine Suche *händereib* ^^

**Comment by FabiApfelkern** [comment]
Anwendung:
 - Filter im privaten Newsstream

**Comment by IvenZ** [comment]
Die erste Version ist auf Dev deployed und kann getestet werden.
Kurze Frage:
Wieso wollen wir Kommentare favorisieren?
Fürs Filtern fällt mir kein Grund ein, da wir sowieso den Eltern-Post zeigen?!
Für die Suche würde es Sinn machen, da diese Posts stärker im Suchergebnis gewichtet werden können.
Sonstige Ideen?

Ihr müsstet auch vielleicht noch mal 1,2 Worte zum Design sagen.
Soll der Stern bleiben?
Anderes wording?

**Comment by IvenZ** [comment]
aktueller stand auf master deployed

**Comment by TeNNoX** [comment]
Im Dropdown steht 'Gemerkte Posts', aber wenn man es auswählt steht da 'Favoriten'...
