### ISSUE TITLE
LDAP-Account zu Local-Account

### ISSUE THREAD

**Issue by FabiApfelkern** [socia-platform/htwplus#86]
Funktion im Admin-Interface, um einen LDAP Account zu einem lokalen Account zu machen.
 - Loginname setzen
 - Passwort setzen
 - Kommentar in die Hilfe, falls das jemand braucht

**Comment by IvenZ** [comment]
Aus gegebenen Anlass habe ich mich mal um dieses Ticket gekümmert.

Als Admin ist es nun möglich Accounts zu editieren.
Ihr findet bei jedem Account einen weiteren "Account konvertieren" Button
Einfach EMail und PW setzen und dann klappt der lokale Login.

**Comment by FabiApfelkern** [comment]
Klasse! Danke,

**Comment by IvenZ** [comment]
deployed on master
