### ISSUE TITLE
Tooltips are not initialized for new comments

### ISSUE THREAD

**Issue by TeNNoX** [socia-platform/htwplus#90]
When posting a new comment, the tooltips for the delete-icon (and in the future also the edit-icon) are not initialized (via $('[rel="tooltip"]').tooltip();)

**Comment by FabiApfelkern** [comment]
Common Problem:
http://jsfiddle.net/6NVQS/1/
http://stackoverflow.com/questions/9958825/how-do-i-bind-twitter-bootstrap-tooltips-to-dynamically-created-elements

**Comment by TeNNoX** [comment]
Somehow I can't get it to work for the popover...

http://jsfiddle.net/n5vn6kg9/

**Comment by FabiApfelkern** [comment]
You have to pass all parameters you need via JavaScript and not via the HTML attribute: http://jsfiddle.net/n5vn6kg9/1/

**Comment by FabiApfelkern** [comment]
Wrong link: https://jsfiddle.net/16fhu4v9/1/

**Comment by TeNNoX** [comment]
Done, thanks :)

**Comment by TeNNoX** [comment]
Ist jetzt rebased auf den Master... hoffe das gibt keine merge-Probleme bei euch, das mit dem Rebase soll man wohl nicht machen, wenn es schon auf einem repository ist. Habe ich dummerweise erst gelesen, nachdem ich es schon gepushed habe.

**Comment by TeNNoX** [comment]
Was haltet ihr davon:
![send](https://cloud.githubusercontent.com/assets/2084639/6608384/cfa85c4a-c846-11e4-8373-76832e84ab49.gif)

**Comment by IvenZ** [comment]
merged in master
