### ISSUE TITLE
Klick auf 'Suchen' auf der Gruppenübersicht bewirkt nichts merkliches

### ISSUE THREAD

**Issue by TeNNoX** [socia-platform/htwplus#92]
Wenn man auf der Seite
https://plus.f4.htw-berlin.de/groups
auf den Link 'suchen' klickt (*Du bist noch keinem Kurs beigetreten. Jetzt einen Kurs* **suchen**), passiert nichts merkliches (außer, das halt die Suche oben fokussiert wird...)

Da das wie ein Link aussieht, aber nichts passiert, ist das ein wenig verwirrend. (Ich spreche aus eigener Erfahrung :P)

**Vorschlag**: Weiterleitung auf die Suchseite? #69

**Comment by IvenZ** [comment]
Ok, habe es mal auf die Suchseite weitergeleitet.

**Comment by IvenZ** [comment]
merged in master
