### ISSUE TITLE
Meldung 'Verbindungsfehler' wenn kein Passwort eingegeben

### ISSUE THREAD

**Issue by TeNNoX** [socia-platform/htwplus#93]
Wenn man bei der Anmeldung kein Passwort eingibt, kommt der Fehler:
´´´"Es gab ein Problem bei der Verbindung zum LDAP-Server. Bitte versuche es später noch einmal. "´´´

Es sollte sowas wie "kein Passwort eigegeben" erscheinen.

**Comment by IvenZ** [comment]
habe mal auf unsere vorhandene error message umgestellt.

**Comment by IvenZ** [comment]
merged in master
