### ISSUE TITLE
post-id wird nicht ersetzt

### ISSUE THREAD

**Issue by TeNNoX** [socia-platform/htwplus#94]
Die Variable wurde im Quellcode mit in den String geschrieben...
![send](https://cloud.githubusercontent.com/assets/2084639/6675873/1052e87e-cc24-11e4-9b56-80d642b4445f.png)

**Comment by TeNNoX** [comment]
Fix incomming...
Für die Zukunft: soll man für sowas immer einen extra issue erstellen?

**Comment by De3pBlu3** [comment]
Nach dem neuen Gitflow wäre das entweder direkt im Feature-Branch
abzuhandeln, oder - wenn es was dringendes ist - als Hotfix-Branch zu
betrachten, der vom Master abgezweigt wird, getagt werden soll und
anschließend in den develop gemerged wird.

2015-03-16 21:37 GMT+01:00 TeNNoX <notifications@github.com>:

**Comment by TeNNoX** [comment]
@De3pBlu3 Also als Hotfix-Material würde ich das nicht betrachten...
Aber das passt auch in keinen Feature-branch mehr?!
Oder ist das Feature "add comments" noch offen? :P

**Comment by IvenZ** [comment]
merged in master
