### ISSUE TITLE
Whitespace bei Posts / Kommentare valide

### ISSUE THREAD

**Issue by De3pBlu3** [socia-platform/htwplus#95]
Wie oben gesagt: man kann sowohl beim Erstellen als auch beim Bearbeiten von Posts / Kommentaren ausschließlich Whitespace angeben.

**Comment by TeNNoX** [comment]
Ich hab die Animation für einen ungültigen Post von dem ganz leeren Post übernommen, hab es aber ein wenig geändert... (finde das ganz ausblenden sieht komisch aus)

![old](https://cloud.githubusercontent.com/assets/2084639/6831321/e0207a1a-d31f-11e4-8917-593ef797cb3d.gif)
![new](https://cloud.githubusercontent.com/assets/2084639/6831285/a94a0a88-d31f-11e4-8b2b-4d12ff8adb5c.gif)

**Comment by IvenZ** [comment]
habe das mal getestet (develop).
wenn ich ein kommentar bearbeite und whitespaces einfüge, bekomme ich gleich das die flash error message. ist das richtig @TeNNoX

**Comment by IvenZ** [comment]
merged in master
