### ISSUE TITLE
Korrektur von 'BaseModel.equals(obj)'

### ISSUE THREAD

**Issue by TeNNoX** [socia-platform/htwplus#96]
Müsste in BaseModel.equals(obj) nicht:
```java
return obj instanceof BaseModel && ...
```
statt:
```java
return obj.getClass() != BaseModel.class && ...
```
stehen?

Denn z.B. **account.getClass()** gibt ja **Account.class** zurück, nicht **BaseModel**...
Dann geht der Vergleich also ins Leere, obwohl die Objekte gleich seien könnten.

**Comment by FabiApfelkern** [comment]
Das steht `obj.getClass() != BaseModel.class`, also ungleich. Was ja Sinn macht. Die Funktion soll prinzipiell nur an abgeleiteten Klassen aufgerufen werde, welche kein BaseModel sind.

**Comment by TeNNoX** [comment]
@FabiApfelkern Das ergibt schon mehr Sinn... ^^
Kleiner Denkfehler... Aber komischerweise hat es bei mir nicht funktioniert...
Weiß aber leider nicht mehr, bei was das war.
