### ISSUE TITLE
JPA persist() statt merge()

### ISSUE THREAD

**Issue by TeNNoX** [socia-platform/htwplus#97]
Eigentlich sollte doch in den **update()**-Funktionen von den ganzen Models die JPA-Funktion **persist(...)** und nicht **merge(...)** verwendet werden, da merge ja ein neues Objekt erstellt.

Der einzige Grund hier merge zu verwenden, wäre wenn das Objekt detached ist, und man es später noch verändern will, ohne das diese Änderungen gespeichert werden... Wofür ich jetzt keinen Grund sehe...

**Comment by FabiApfelkern** [comment]
Du hast grundsätzlich Recht. Unsere update-Funktion ist nicht ganz sauber. Wir haben das ursprünglich von einem offiziellen Beispiel von Play übernommen, aber mittlerweile festgestellt, dass es nicht ganz korrekt ist, aber funktioniert. Tatsächlich braucht man werder persist noch merge. Unsere Entities sind alle atached, daher sollten änderungen automatisch in die Datenbank geschrieben werden. Iven hat das letztens praktisch getestet. Wir sollten das nochmal sauber recherchieren. Das Problem ist auch, dass JPA ein Standard ist, der nicht immer richtig implementiert ist. Wenn man persist benutzt soll es passieren können, dass einen komplett neue Entity angelegt wird.

**Comment by IvenZ** [comment]
Ich habe mir das eben noch einmal angeguckt, da ich für die Account Update-Funktion einen sauberen (re)index call haben wollte.

Irgendwie hat alles nicht funktioniert. :-D

Hier noch mal meine 2 Pfennige:
Wird ein neue Entity erstellt, welche wir in der DB speichern möchten, muss weiterhin persist() aufgerufen werden. Wenn wir eine Entity aus der DB holen werden alle Änderungen vom EM AUTOMATISCH mit der DB synchronisiert. Das Ding nennt sich dann "managed entity" und der Vorgang "Automatic Dirty Checking" (Falls jemand googlen möchte).

In diese automatische Synchonisation kann man natürlich eingreifen. Ich finde es allerdings nicht so schlimm, solang man weiß, was passiert.

D.h, wir müssten einfach nur alle update() Funktionen aus unserem Code schmeißen.
Die bewirken wie richtig angemerkt im Moment sowieso nix.

**Comment by IvenZ** [comment]
So, ich habe mal angefangen das umzubauen, allerdings bin ich schon wieder auf unseren alten Freund: "no em bound to this thread" gestoßen.

Ich hatte gehofft, dass ich mit Annotationen die Index-Geschichten anstoßen kann.
Scheint aber keine coole Lösung zu sein.

Also wohl doch per Hand :(

**Comment by FabiApfelkern** [comment]
Nicht so schnell aufgeben. Wir sollten die EM Geschichte lieber mal richtig verstehen und damit arbeiten und nicht drumrum bauen.

**Comment by IvenZ** [comment]
Ich habe mein Vorhaben gerade noch einmal in ein neues, frisches Projekt gebaut und da gab es keine Probleme. Ich befürchte, dass wir irgendwann an irgendeiner Stelle mal einen DB-Aufruf falsch implementiert haben.

**Comment by FabiApfelkern** [comment]
Kannst du den Fehler bei uns einbauen und in einem Branch pushen. Ich will mir das mal angucken die Woche.

**Comment by IvenZ** [comment]
Zieh dir einfach das Ding hier.
Das müsste knallen, sobald du ein Profil updatest.

**Comment by FabiApfelkern** [comment]
Habs mir angeguckt. Ich versteh das nicht genau. Was ist denn dein Plan? Du rufst die indexAccount im Controller auf UND hast eine Annonation dran. Wenn ich die Annotation wegmache geht alles, logisch. Wenn ich den Aufruf im Controller rausnehme und die Annotation benutze wird die Methode nie aufgerufen, es gibt auch kein Fehler. Diese @PostUpdate und @PostPersist gehen einfach nicht.

**Comment by TeNNoX** [comment]
Würde mir das auch die Tage mal anschauen, vielleicht hat es was gebracht, mir das ganze Zeug durchzulesen :P

**Comment by IvenZ** [comment]
Habe den Aufruf noch einmal raus genommen. Dabei die Annotation von der indexAccount Methode funktioniert, müsst ihr das Account Objekt beim speichern verändern. (Ich änder immer den Studiengang)
